--Homework 07.02.2019:
SELECT DISTINCT COMPANY FROM ORDERS o1 INNER JOIN PRODUCTS p1 ON o1.PRODUCT = p1.product_id INNER JOIN CUSTOMERS c1 ON o1.cust = c1.cust_num
WHERE p1.DESCRIPTION LIKE '%a%' OR p1.DESCRIPTION LIKE '%A%' OR p1.description LIKE '%А%'  OR p1.description LIKE '%а%';
--
SELECT ORDER_NUM, AMOUNT, COMPANY, CREDIT_LIMIT  FROM ORDERS, CUSTOMERS  WHERE CUST = CUST_NUM;
SELECT ORDER_NUM, AMOUNT, COMPANY, CREDIT_LIMIT  FROM ORDERS o1 INNER JOIN CUSTOMERS o2  ON o1.cust = o2.cust_num;
SELECT   order_num,  amount, company, credit_limit FROM (SELECT * FROM orders INNER JOIN customers ON orders.cust = customers.cust_num );
--
SELECT NAME, CITY, REGION  FROM SALESREPS, OFFICES  WHERE REP_OFFICE = OFFICE;
SELECT NAME, CITY, REGION  FROM SALESREPS o1 INNER JOIN OFFICES o2  ON o1.rep_office=o2.office; 
--
SELECT CITY, NAME, TITLE  FROM OFFICES, SALESREPS  WHERE MGR = EMPL_NUM;
SELECT CITY, NAME, TITLE  FROM OFFICES o1 INNER JOIN SALESREPS o2 ON o1.mgr = o2.empl_num; 
--
SELECT CITY, NAME, TITLE  FROM OFFICES, SALESREPS    WHERE MGR = EMPL_NUM AND  TARGET > 600.00;
SELECT CITY, NAME, TITLE  FROM OFFICES o1 INNER JOIN SALESREPS o2  ON o1.mgr = o2.empl_num AND  TARGET > 600.00;
--
SELECT ORDER_NUM, AMOUNT, DESCRIPTION  FROM ORDERS, PRODUCTS  WHERE MFR = MFR_ID AND PRODUCT = PRODUCT_ID;
SELECT ORDER_NUM, AMOUNT, DESCRIPTION  FROM ORDERS o1 INNER JOIN PRODUCTS o2 ON o1.mfr = o2.mfr_id AND PRODUCT = PRODUCT_ID;
--
SELECT ORDER_NUM, AMOUNT, COMPANY, NAME FROM ORDERS, CUSTOMERS, SALESREPS WHERE CUST = CUST_NUM AND	  REP = EMPL_NUM AND  AMOUNT > 700;
SELECT ORDER_NUM, AMOUNT, COMPANY, NAME FROM ORDERS t1 INNER JOIN CUSTOMERS t2 ON t1.cust = t2.cust_num INNER JOIN SALESREPS c1 ON
c1.empl_num = t1.rep AND AMOUNT > 700;
--
SELECT ORDER_NUM, AMOUNT, COMPANY, NAME	FROM ORDERS, CUSTOMERS, SALESREPS WHERE CUST = CUST_NUM AND	  CUST_REP = EMPL_NUM AND	  AMOUNT > 700;
SELECT ORDER_NUM, AMOUNT, COMPANY, NAME FROM ORDERS t1 INNER JOIN CUSTOMERS t2 ON t1.cust = t2.cust_num INNER JOIN SALESREPS c1 ON
c1.empl_num = t2.cust_rep AND AMOUNT > 700;
--
SELECT ORDER_NUM, AMOUNT, COMPANY, NAME, CITY	FROM ORDERS, CUSTOMERS, SALESREPS, OFFICES WHERE CUST = CUST_NUM AND CUST_REP = EMPL_NUM AND 
REP_OFFICE = OFFICE AND	  AMOUNT > 700;

SELECT ORDER_NUM, AMOUNT, COMPANY, NAME, CITY	FROM ORDERS t1 INNER JOIN  CUSTOMERS t2 ON t1.cust=t2.cust_num INNER JOIN  SALESREPS t3 ON
t3.empl_num = t2.cust_rep INNER JOIN  OFFICES t4 ON t4.office = t3.rep_office  AND	  AMOUNT > 700;
--
SELECT ORDER_NUM, AMOUNT, ORDER_DATE, NAME	FROM ORDERS, SALESREPS WHERE ORDER_DATE = HIRE_DATE;
SELECT ORDER_NUM, AMOUNT, ORDER_DATE, NAME	FROM ORDERS t1 INNER JOIN  SALESREPS t2 ON t1.order_date=t2.hire_date;
--
SELECT NAME, QUOTA, CITY, TARGET	FROM SALESREPS, OFFICES WHERE QUOTA > TARGET;
SELECT NAME, QUOTA, CITY, TARGET	FROM SALESREPS t1 INNER JOIN  OFFICES t2 ON   t1.quota > t2.target;
SELECT 
    name,
    quota,
    city,
    target
FROM
    (
        SELECT
            *
        FROM
            salesreps
            INNER JOIN offices ON salesreps.quota > offices.target
    )
WHERE
    quota > target;
     
--    
SELECT NAME, SALESREPS.SALES, CITY	FROM SALESREPS, OFFICES	WHERE REP_OFFICE = OFFICE;
SELECT NAME, t1.sales,  CITY	FROM OFFICES t2  INNER JOIN  SALESREPS t1 ON t1.rep_office=t2.office;
SELECT
    name,
    sales,
    city
FROM
    (
        SELECT
            *
        FROM
            salesreps
            INNER JOIN (
                SELECT
                    city,
                    office
                FROM
                    offices
            ) ON salesreps.rep_office = office
    );
--
SELECT NAME, SALESREPS.SALES, CITY	FROM SALESREPS, OFFICES	WHERE REP_OFFICE = OFFICE;
SELECT NAME, t1.SALES, CITY FROM SALESREPS t1 INNER JOIN OFFICES t2 ON t1.REP_OFFICE = t2. OFFICE;
--
SELECT * 	FROM SALESREPS, OFFICES	WHERE REP_OFFICE = OFFICE;
SELECT * FROM SALESREPS t1 INNER JOIN OFFICES t2 ON t1.REP_OFFICE =  t2.OFFICE;
--
SELECT SALESREPS.*, CITY, REGION	FROM SALESREPS, OFFICES	WHERE REP_OFFICE = OFFICE;
SELECT t1.*, CITY, REGION FROM SALESREPS t1 INNER JOIN OFFICES t2 ON t1.REP_OFFICE =  t2.OFFICE;
--
SELECT EMPS.NAME, MGRS.NAME	FROM SALESREPS EMPS, SALESREPS MGRS	WHERE EMPS.MANAGER = MGRS.EMPL_NUM;
SELECT SALESREPS.NAME, MGRS.NAME	FROM SALESREPS, SALESREPS MGRS	WHERE SALESREPS.MANAGER = MGRS.EMPL_NUM;
SELECT t1.NAME, t2.NAME FROM SALESREPS t1
INNER JOIN SALESREPS t2 ON t1.MANAGER = t2.EMPL_NUM;
--
SELECT SALESREPS.NAME, SALESREPS.QUOTA, MGRS.QUOTA	FROM SALESREPS, SALESREPS MGRS	WHERE SALESREPS.MANAGER = MGRS.EMPL_NUM
	AND SALESREPS.QUOTA > MGRS.QUOTA;
SELECT t1.NAME, t1.QUOTA, t2.QUOTA FROM SALESREPS t1 INNER JOIN SALESREPS t2 ON t1.MANAGER = t2.EMPL_NUM
WHERE t1.QUOTA > t2.QUOTA;
--
SELECT EMPS.NAME, EMP_OFFICE.CITY, MGRS.NAME, MGR_OFFICE.CITY
	FROM SALESREPS EMPS, SALESREPS MGRS, OFFICES EMP_OFFICE,
	OFFICES MGR_OFFICE
	WHERE EMPS.REP_OFFICE = EMP_OFFICE.OFFICE
	AND MGRS.REP_OFFICE = MGR_OFFICE.OFFICE
	AND EMPS.MANAGER = MGRS.EMPL_NUM
	AND EMPS.REP_OFFICE <> MGRS.REP_OFFICE;
    
SELECT t1.NAME, t2.CITY, t3.NAME, t4.CITY FROM SALESREPS t1
INNER JOIN OFFICES t2 ON t1.REP_OFFICE = t2.OFFICE
INNER JOIN SALESREPS t3 ON t1.MANAGER = t3.EMPL_NUM
INNER JOIN OFFICES t4 ON t1.REP_OFFICE  = t4.OFFICE AND t1.REP_OFFICE <> t3.REP_OFFICE;
--
SELECT AVG(QUOTA), AVG(SALES) FROM SALESREPS;

SELECT NAME, CITY	FROM SALESREPS, OFFICES;

SELECT AVG(100 * (SALES/QUOTA)) FROM SALESREPS;

SELECT AVG(100 * (SALES/QUOTA)) PROCENT FROM SALESREPS;

SELECT SUM(QUOTA), SUM(SALES) FROM SALESREPS;

SELECT SUM(AMOUNT) FROM ORDERS t1
INNER JOIN SALESREPS t2  ON t1.REP =t2.EMPL_NUM
WHERE NAME = 'Дима Маликов';
--
SELECT AVG(PRICE)
	FROM PRODUCTS
	WHERE MFR_ID = 'ACI';
--    
SELECT AVG(AMOUNT) FROM ORDERS WHERE  CUST = 2103;
--
SELECT MIN(QUOTA), MAX(QUOTA) FROM SALESREPS;
--
SELECT MIN(ORDER_DATE) FROM ORDERS ;
--
SELECT MAX(100 * (SALES/QUOTA)) FROM SALESREPS;
--
SELECT COUNT(CUST_NUM) FROM CUSTOMERS ;
--
SELECT COUNT(NAME) FROM SALESREPS WHERE SALES > QUOTA;
--
SELECT COUNT(AMOUNT)FROM ORDERS WHERE  AMOUNT > 250;
--
SELECT COUNT(*) FROM  ORDERS WHERE  AMOUNT > 250;
--
SELECT AVG(AMOUNT), SUM(AMOUNT), (100 * AVG(AMOUNT/CREDIT_LIMIT)), (100 * AVG(AMOUNT/QUOTA))
	FROM ORDERS, CUSTOMERS, SALESREPS
	WHERE CUST = CUST_NUM AND REP = EMPL_NUM;
    
SELECT AVG(AMOUNT), SUM(AMOUNT), (100 * AVG(AMOUNT/CREDIT_LIMIT)), (100 * AVG(AMOUNT/QUOTA)) FROM  ORDERS t1
INNER JOIN CUSTOMERS t2 ON t1.CUST = t2.CUST_NUM
INNER JOIN SALESREPS t3 ON t1.REP = t3.EMPL_NUM;