package com.mateacademy.lessons16.entry;

// Generated Feb 2, 2019 5:38:52 PM by Hibernate Tools 5.2.10.Final

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Offices generated by hbm2java
 */
@Entity
@Table(name = "OFFICES", schema = "MA_STUDENT")
public class Offices implements java.io.Serializable {

    private BigDecimal office;
    private Salesreps salesreps;
    private String city;
    private String region;
    private BigDecimal target;
    private BigDecimal sales;
    private Set<Salesreps> salesrepses = new HashSet<Salesreps>(0);

    public Offices() {
    }

    public Offices(BigDecimal office, String city, String region, BigDecimal sales) {
        this.office = office;
        this.city = city;
        this.region = region;
        this.sales = sales;
    }

    public Offices(BigDecimal office, Salesreps salesreps, String city, String region, BigDecimal target,
                   BigDecimal sales, Set<Salesreps> salesrepses) {
        this.office = office;
        this.salesreps = salesreps;
        this.city = city;
        this.region = region;
        this.target = target;
        this.sales = sales;
        this.salesrepses = salesrepses;
    }

    @Id

    @Column(name = "OFFICE", unique = true, nullable = false, precision = 22, scale = 0)
    public BigDecimal getOffice() {
        return this.office;
    }

    public void setOffice(BigDecimal office) {
        this.office = office;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "MGR")
    public Salesreps getSalesreps() {
        return this.salesreps;
    }

    public void setSalesreps(Salesreps salesreps) {
        this.salesreps = salesreps;
    }

    @Column(name = "CITY", nullable = false, length = 40)
    public String getCity() {
        return this.city;
    }

    public void setCity(String city) {
        this.city = city;
    }

    @Column(name = "REGION", nullable = false, length = 30)
    public String getRegion() {
        return this.region;
    }

    public void setRegion(String region) {
        this.region = region;
    }

    @Column(name = "TARGET", precision = 22, scale = 0)
    public BigDecimal getTarget() {
        return this.target;
    }

    public void setTarget(BigDecimal target) {
        this.target = target;
    }

    @Column(name = "SALES", nullable = false, precision = 22, scale = 0)
    public BigDecimal getSales() {
        return this.sales;
    }

    public void setSales(BigDecimal sales) {
        this.sales = sales;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "offices")
    public Set<Salesreps> getSalesrepses() {
        return this.salesrepses;
    }

    public void setSalesrepses(Set<Salesreps> salesrepses) {
        this.salesrepses = salesrepses;
    }

}
