package com.mateacademy.lessons16.entry;

// Generated Feb 2, 2019 5:38:52 PM by Hibernate Tools 5.2.10.Final

import com.mateacademy.lessons16.entry.Orders;

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Products generated by hbm2java
 */
@Entity
@Table(name = "PRODUCTS", schema = "MA_STUDENT")
public class Products implements java.io.Serializable {

    private String productId;
    private String mfrId;
    private String description;
    private BigDecimal price;
    private BigDecimal qtyOnHand;
    private Set<Orders> orderses = new HashSet<Orders>(0);

    public Products() {
    }

    public Products(String productId) {
        this.productId = productId;
    }

    public Products(String productId, String mfrId, String description, BigDecimal price, BigDecimal qtyOnHand,
                    Set<Orders> orderses) {
        this.productId = productId;
        this.mfrId = mfrId;
        this.description = description;
        this.price = price;
        this.qtyOnHand = qtyOnHand;
        this.orderses = orderses;
    }

    @Id

    @Column(name = "PRODUCT_ID", unique = true, nullable = false, length = 5)
    public String getProductId() {
        return this.productId;
    }

    public void setProductId(String productId) {
        this.productId = productId;
    }

    @Column(name = "MFR_ID", length = 3)
    public String getMfrId() {
        return this.mfrId;
    }

    public void setMfrId(String mfrId) {
        this.mfrId = mfrId;
    }

    @Column(name = "DESCRIPTION", length = 50)
    public String getDescription() {
        return this.description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    @Column(name = "PRICE", precision = 22, scale = 0)
    public BigDecimal getPrice() {
        return this.price;
    }

    public void setPrice(BigDecimal price) {
        this.price = price;
    }

    @Column(name = "QTY_ON_HAND", precision = 22, scale = 0)
    public BigDecimal getQtyOnHand() {
        return this.qtyOnHand;
    }

    public void setQtyOnHand(BigDecimal qtyOnHand) {
        this.qtyOnHand = qtyOnHand;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "products")
    public Set<Orders> getOrderses() {
        return this.orderses;
    }

    public void setOrderses(Set<Orders> orderses) {
        this.orderses = orderses;
    }

    /**
     * toString
     * @return String
     */
    public String toString() {
        StringBuffer buffer = new StringBuffer();

        buffer.append(getClass().getName()).append("@").append(Integer.toHexString(hashCode())).append(" [");
        buffer.append("productId").append("='").append(getProductId()).append("' ");
        buffer.append("mfrId").append("='").append(getMfrId()).append("' ");
        buffer.append("description").append("='").append(getDescription()).append("' ");
        buffer.append("price").append("='").append(getPrice()).append("' ");
        buffer.append("qtyOnHand").append("='").append(getQtyOnHand()).append("' ");
        buffer.append("]");

        return buffer.toString();
    }

}
