package com.mateacademy.lessons16.entry;
// Generated Feb 2, 2019 5:38:52 PM by Hibernate Tools 5.2.10.Final

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Salesreps generated by hbm2java
 */
@Entity
@Table(name = "SALESREPS", schema = "MA_STUDENT")
public class Salesreps implements java.io.Serializable {

    private BigDecimal emplNum;
    private Offices offices;
    private Salesreps salesreps;
    private String name;
    private BigDecimal age;
    private String title;
    private Date hireDate;
    private BigDecimal quota;
    private BigDecimal sales;
    private Set<Offices> officeses = new HashSet<Offices>(0);
    private Set<Salesreps> salesrepses = new HashSet<Salesreps>(0);
    private Set<Orders> orderses = new HashSet<Orders>(0);
    private Set<Customers> customerses = new HashSet<Customers>(0);

    public Salesreps() {
    }

    public Salesreps(BigDecimal emplNum, Date hireDate) {
        this.emplNum = emplNum;
        this.hireDate = hireDate;
    }

    public Salesreps(BigDecimal emplNum, Offices offices, Salesreps salesreps, String name, BigDecimal age,
                     String title, Date hireDate, BigDecimal quota, BigDecimal sales, Set<Offices> officeses,
                     Set<Salesreps> salesrepses, Set<Orders> orderses, Set<Customers> customerses) {
        this.emplNum = emplNum;
        this.offices = offices;
        this.salesreps = salesreps;
        this.name = name;
        this.age = age;
        this.title = title;
        this.hireDate = hireDate;
        this.quota = quota;
        this.sales = sales;
        this.officeses = officeses;
        this.salesrepses = salesrepses;
        this.orderses = orderses;
        this.customerses = customerses;
    }

    @Id

    @Column(name = "EMPL_NUM", unique = true, nullable = false, precision = 22, scale = 0)
    public BigDecimal getEmplNum() {
        return this.emplNum;
    }

    public void setEmplNum(BigDecimal emplNum) {
        this.emplNum = emplNum;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "REP_OFFICE")
    public Offices getOffices() {
        return this.offices;
    }

    public void setOffices(Offices offices) {
        this.offices = offices;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "MANAGER")
    public Salesreps getSalesreps() {
        return this.salesreps;
    }

    public void setSalesreps(Salesreps salesreps) {
        this.salesreps = salesreps;
    }

    @Column(name = "NAME", length = 30)
    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    @Column(name = "AGE", precision = 22, scale = 0)
    public BigDecimal getAge() {
        return this.age;
    }

    public void setAge(BigDecimal age) {
        this.age = age;
    }

    @Column(name = "TITLE", length = 40)
    public String getTitle() {
        return this.title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "HIRE_DATE", nullable = false, length = 7)
    public Date getHireDate() {
        return this.hireDate;
    }

    public void setHireDate(Date hireDate) {
        this.hireDate = hireDate;
    }

    @Column(name = "QUOTA", precision = 22, scale = 0)
    public BigDecimal getQuota() {
        return this.quota;
    }

    public void setQuota(BigDecimal quota) {
        this.quota = quota;
    }

    @Column(name = "SALES", precision = 22, scale = 0)
    public BigDecimal getSales() {
        return this.sales;
    }

    public void setSales(BigDecimal sales) {
        this.sales = sales;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "salesreps")
    public Set<Offices> getOfficeses() {
        return this.officeses;
    }

    public void setOfficeses(Set<Offices> officeses) {
        this.officeses = officeses;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "salesreps")
    public Set<Salesreps> getSalesrepses() {
        return this.salesrepses;
    }

    public void setSalesrepses(Set<Salesreps> salesrepses) {
        this.salesrepses = salesrepses;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "salesreps")
    public Set<Orders> getOrderses() {
        return this.orderses;
    }

    public void setOrderses(Set<Orders> orderses) {
        this.orderses = orderses;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "salesreps")
    public Set<Customers> getCustomerses() {
        return this.customerses;
    }

    public void setCustomerses(Set<Customers> customerses) {
        this.customerses = customerses;
    }

}
