package com.mateacademy.lessons15v2;
// Generated Jan 26, 2019 11:24:41 AM by Hibernate Tools 5.2.10.Final


import java.math.BigDecimal;
import java.util.Date;

/**
 * Order generated by hbm2java
 */
public class Order  implements java.io.Serializable {


     private BigDecimal orderNum;
     private Product product;
     private Date orderDate;
     private String mfr;
     private BigDecimal qty;
     private BigDecimal amount;

    public Order() {
    }

	
    public Order(BigDecimal orderNum, Product product) {
        this.orderNum = orderNum;
        this.product = product;
    }
    public Order(BigDecimal orderNum, Product product, Date orderDate, String mfr, BigDecimal qty, BigDecimal amount) {
       this.orderNum = orderNum;
       this.product = product;
       this.orderDate = orderDate;
       this.mfr = mfr;
       this.qty = qty;
       this.amount = amount;
    }
   
    public BigDecimal getOrderNum() {
        return this.orderNum;
    }

    public void setOrderNum(BigDecimal orderNum) {
        this.orderNum = orderNum;
    }
    public Product getProduct() {
        return this.product;
    }
    
    public void setProduct(Product product) {
        this.product = product;
    }
    public Date getOrderDate() {
        return this.orderDate;
    }
    
    public void setOrderDate(Date orderDate) {
        this.orderDate = orderDate;
    }
    public String getMfr() {
        return this.mfr;
    }
    
    public void setMfr(String mfr) {
        this.mfr = mfr;
    }
    public BigDecimal getQty() {
        return this.qty;
    }
    
    public void setQty(BigDecimal qty) {
        this.qty = qty;
    }
    public BigDecimal getAmount() {
        return this.amount;
    }
    
    public void setAmount(BigDecimal amount) {
        this.amount = amount;
    }

    /**
     * toString
     * @return String
     */
     public String toString() {
	  StringBuffer buffer = new StringBuffer();

      buffer.append(getClass().getName()).append("@").append(Integer.toHexString(hashCode())).append(" [");
      buffer.append("orderNum").append("='").append(getOrderNum()).append("' ");			
      buffer.append("product").append("='").append(getProduct()).append("' ");			
      buffer.append("orderDate").append("='").append(getOrderDate()).append("' ");			
      buffer.append("mfr").append("='").append(getMfr()).append("' ");			
      buffer.append("qty").append("='").append(getQty()).append("' ");			
      buffer.append("amount").append("='").append(getAmount()).append("' ");			
      buffer.append("]");
      
      return buffer.toString();
     }



}


